name: CI/CD ChronoTrak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: docker
    container:
      image: docker:latest
      network: "host"
      options: --privileged
    steps:
      - name: Configuration du runner
        run: |
          apk add --no-cache git nodejs npm curl

      - name: Checkout du code avec actions/checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.sha }}

      # Authentification au registre
      - name: Login au registre Docker
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login forge.apacher.eu -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      # Construction et push de l'image
      - name: Build et push de l'image Docker
        run: |
          docker buildx build --provenance=false --push --tag forge.apacher.eu/aurelien-dazy/chronotrak:latest .

      # Analyse de sécurité avec Trivy
      - name: Installation et exécution de Trivy
        run: |
          apk add --no-cache curl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy image forge.apacher.eu/aurelien-dazy/chronotrak:latest --severity HIGH,CRITICAL

  deploy:
    needs: build-and-push
    runs-on: docker
    container:
      image: alpine:latest  # Image légère
      options: --privileged --network host
    steps:
      # Installation de Docker et des dépendances
      - name: Installation de Docker et des dépendances
        run: |
          apk add --no-cache docker-cli docker openrc bash openssh-client
          rc-update add docker boot
          service docker start

      # Configuration de la clé SSH (ed25519)
      - name: Configuration de la clé SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROD_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t ed25519 -H ${{ secrets.PROD_SSH_HOST }} >> ~/.ssh/known_hosts

      # Test de connexion SSH
      - name: Test de connexion SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.PROD_SSH_PORT }} ${{ secrets.PROD_SSH_USERNAME }}@${{ secrets.PROD_SSH_HOST }} "echo 'Connexion SSH réussie'"

      # Déploiement sur le serveur de production
      - name: Déploiement sur le serveur de production
        run: |
          ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.PROD_SSH_PORT }} ${{ secrets.PROD_SSH_USERNAME }}@${{ secrets.PROD_SSH_HOST }} "
            set -e
            cd ${{ secrets.PROJECT_DIRECTORY }}
            docker login forge.apacher.eu -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
            ENVIRONMENT=production docker compose pull
            ENVIRONMENT=production docker compose up -d
            docker logout forge.apacher.eu
          "