name: CI/CD ChronoTrak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  build-and-push:
    runs-on: docker
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      # Authentification au registre
      - name: Login au registre Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_REPOSITORY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Construction et push de l'image
      - name: Build et push de l'image Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: forge.apacher.eu/aurelien-dazy/chronotrak:latest
          provenance: false

      # Analyse de sécurité avec Trivy
      - name: Scan de l'image avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'forge.apacher.eu/aurelien-dazy/chronotrak:latest'
          format: 'table'
          exit-code: '0'  # Ne pas échouer le build en cas de vulnérabilités (vous pouvez passer à 1 pour échouer)
          severity: 'CRITICAL,HIGH'  # Scan seulement pour les vulnérabilités critiques et élevées

  deploy:
    needs: build-and-push  # Attend que le job build-and-push soit terminé
    runs-on: docker
    steps:
      - name: Déploiement sur le serveur de production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          port: ${{ secrets.PROD_SSH_PORT }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd ${{ secrets.PROJECT_DIRECTORY }}
            docker login forge.apacher.eu -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
            ENVIRONMENT=production docker compose pull
            ENVIRONMENT=production docker compose up -d
            docker logout forge.apacher.eu