"""Add checklist items table

Revision ID: 2d7c163ec536
Revises: set_time_tracking_enabled_default
Create Date: 2025-05-23 12:56:48.511062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7c163ec536'
down_revision = 'set_time_tracking_enabled_default'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index('idx_client_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_client_name_slug', ['name', 'slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_contact_name'), ['contact_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_slug'), ['slug'], unique=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('time_tracking_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('time_tracking_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_slug'))
        batch_op.drop_index(batch_op.f('ix_client_name'))
        batch_op.drop_index(batch_op.f('ix_client_created_at'))
        batch_op.drop_index(batch_op.f('ix_client_contact_name'))
        batch_op.drop_index('idx_client_name_slug')
        batch_op.drop_index('idx_client_created_at')

    op.drop_table('checklist_item')
    # ### end Alembic commands ###
