"""Add task_created notification preference

Revision ID: 35d68cffdfe2
Revises: a51ddf5b4c65
Create Date: 2025-08-12 22:18:48.725846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d68cffdfe2'
down_revision = 'a51ddf5b4c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_created', sa.Boolean(), nullable=True, server_default='1'))
    
    # Mettre à jour les enregistrements existants
    op.execute("UPDATE notification_preference SET task_created = 1 WHERE task_created IS NULL")
    
    # Rendre la colonne non nullable après la mise à jour
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.alter_column('task_created', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.drop_column('task_created')

    # ### end Alembic commands ###
