"""Convert time tracking to minutes

Revision ID: a51ddf5b4c65
Revises: add_user_pinned_task
Create Date: 2025-06-02 21:32:58.372172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51ddf5b4c65'
down_revision = 'add_user_pinned_task'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, add new columns
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('actual_minutes', sa.Integer(), nullable=True))

    with op.batch_alter_table('time_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minutes', sa.Integer(), nullable=True))

    # Then, convert the data
    op.execute("UPDATE task SET estimated_minutes = ROUND(estimated_time * 60) WHERE estimated_time IS NOT NULL")
    op.execute("UPDATE task SET actual_minutes = ROUND(actual_time * 60) WHERE actual_time IS NOT NULL")
    op.execute("UPDATE time_entry SET minutes = ROUND(hours * 60) WHERE hours IS NOT NULL")

    # Finally, make the new columns non-nullable and drop old columns
    with op.batch_alter_table('time_entry', schema=None) as batch_op:
        batch_op.alter_column('minutes', nullable=False)
        batch_op.drop_column('hours')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('actual_time')
        batch_op.drop_column('estimated_time')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('initial_credit',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               postgresql_using='initial_credit::integer',
               existing_nullable=False)
        batch_op.alter_column('remaining_credit',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               postgresql_using='remaining_credit::integer',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('remaining_credit',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('initial_credit',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('actual_time', sa.FLOAT(), nullable=True))
        # Convert minutes back to hours
        op.execute("UPDATE task SET estimated_time = estimated_minutes / 60.0 WHERE estimated_minutes IS NOT NULL")
        op.execute("UPDATE task SET actual_time = actual_minutes / 60.0 WHERE actual_minutes IS NOT NULL")
        batch_op.drop_column('actual_minutes')
        batch_op.drop_column('estimated_minutes')

    with op.batch_alter_table('time_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours', sa.FLOAT(), nullable=True))
        # Convert minutes back to hours
        op.execute("UPDATE time_entry SET hours = minutes / 60.0 WHERE minutes IS NOT NULL")
        batch_op.alter_column('hours', nullable=False)
        batch_op.drop_column('minutes')

    # ### end Alembic commands ###
