"""Add pinned tasks feature

Revision ID: add_pinned_tasks
Revises: 2d7c163ec536
Create Date: 2025-05-24 10:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "add_pinned_tasks"
down_revision = "2d7c163ec536"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_pinned", sa.Boolean(), nullable=False, server_default="0"))
        batch_op.create_index("idx_task_is_pinned", ["is_pinned"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_index("idx_task_is_pinned")
        batch_op.drop_column("is_pinned")
    # ### end Alembic commands ###
