"""Add position field to Task model

Revision ID: add_position_to_task
Revises: bad0b05a6b6f
Create Date: 2025-01-27 13:55:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "add_position_to_task"
down_revision = "bad0b05a6b6f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(sa.Column("position", sa.Integer(), nullable=True, server_default="0"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_column("position")
    # ### end Alembic commands ###
