"""Add parent_id to comments for replies

Revision ID: ce5f817a275a
Revises: 2d7c163ec536
Create Date: 2025-05-25 22:21:43.369101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce5f817a275a'
down_revision = '2d7c163ec536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_comment_parent_id', 'comment', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_parent_id', type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
