"""Add time_tracking_enabled to Project model

Revision ID: d1a7cda8cd78
Revises: 6a79ac14d01b
Create Date: 2025-05-17 12:18:03.250427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a7cda8cd78'
down_revision = '6a79ac14d01b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_tracking_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('time_tracking_enabled')

    # ### end Alembic commands ###
