"""Add is_favorite field to Project model

Revision ID: d8554cc957ca
Revises: add_position_to_task
Create Date: 2025-09-11 11:04:53.030017

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d8554cc957ca"
down_revision = "add_position_to_task"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_favorite", sa.Boolean(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.drop_column("is_favorite")
    # ### end Alembic commands ###
